# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands:
  - msbuild
  - visualstudio

steps:
# ...
# Use NuGet 5
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5'
  inputs:
    versionSpec: 5.x
# ...
# Restore NuGet packages.
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    feedsToUse: config
# ...
# Version with GitVersion
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false
# ...
# Build Solution
- task: VSBuild@1
  displayName: 'Build solution Orleans.Security.Build.sln'
  inputs:
    solution: Orleans.Security.Build.sln
    platform: 'any cpu'
    configuration: release
    clean: true
# ...
# Run Tests
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--logger:trx'
# ...
# Publish Test Results
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: 'test/**/*.trx'
# ...
# NuGet pack Orleans.Security.Build.sln
- task: DotNetCoreCLI@2
  displayName: 'NuGet pack Orleans.Security.Build.sln'
  inputs:
    command: pack
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.SemVer
    packagesToPack: Orleans.Security.Build.sln
# ...
# Push NuGet packs to feed
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: '5a6d822d-5d9b-4d9a-8ce4-23803c42a92f/d861be06-fd69-4794-9c74-dd8b05950c7e'
