language: ruby
rvm:
  - 2.3.0
env:
  - TRAVIS_NODE_VERSION="9.3.0"

install:
  - npm install
  - gem install bundler --version '>=1.17.1'
  - bundle install

script:
  - npm run test
  - bundle exec jekyll build
